version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27018:27017"  # host:container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  # RabbitMQ with management UI
  rabbitmq_node:
    image: rabbitmq:3-management
    container_name: rabbitmq_node
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/users?authSource=admin

  # Task Service
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq_node
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/tasks?authSource=admin

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq_node

volumes:
  mongo_data:
